config/routes.rb
Rails.application.routes.draw do
  root 'todos#index'
  resources :todos
=begin
  get '/' do
    todos_controller.index
  end
=end
#新しいURLの追加
  resources :todos do
    member do
      patch 'status'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, presence: true
  validates :status, presence: true
  validates :priority, presence: true,
    numericality: {
      only_integer: true,
      greater_than_or_equal_to: 0,
      less_than_or_equal_to: 5,
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  #only 以下のメソッドの前に before action として set_todo メソッドへ
  before_action :set_todo, only: [:show, :edit, :update, :status, :destroy]

  # GET /todos
  # GET /todos.json
  # resources : todo
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    #入力されたものがtodo_paramsに入る
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        #成功
        #各formatでの表示結果が以下
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        #失敗 戻される
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  #バリデーションに失敗したら表す
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
#リダイレクトし、notice 以下のメッセージを返す
  def status
    @todo.status = params[:status]
    @todo.save!
    redirect_to root_url, notice: "「#{@todo.title}」が完了しました"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    #permit()内に扱いが許可されてるパラメータを記述
    def todo_params
      params.require(:todo).permit(:title, :body, :status, :priority)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h1>My application</h1>


  <div id= "wrapper">
    <header>
      <%= link_to '新しいTodo', new_todo_path %>
    </header>

    <%= yield %>
  </div>

  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo, local: true) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <%# formタグでテキスト入力 %>
  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <%# formタグで数字選択 %>
  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.number_field :priority %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Status</th>
      <th>Priority</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= link_to todo do %><%= todo.title %><% end %></td>
        <%# 囲んだところがリンクになる %>
        <td><%= todo.body %></td>
        <td><%= todo.status %></td>
        <td><%= todo.priority %></td>
        <%# statusを1にしてtodo statusコントローラーへ %>
        <td><%= link_to '完了', status_todo_path(todo, status: 1), method: :patch %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @todo.body %>
</p>

<p>
  <strong>Status:</strong>
  <%= @todo.status %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @todo.priority %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>